### PR TITLE
Option to set random name generator seed

### PR DESCRIPTION
**Pull request by luismavs**
Hi,

I've added the option of run_with_set_random_seed to fix the seed for the (pseudo) random number generator. This way, you are guaranteed to get the same random name if you provide the same seed.
Implemented with decorators.

### CODE REVIEW

**Comment by f-rosato** [comment]
I also felt the need for something similar, but I'd like to discuss this proposed solution. Setting and resetting `random.seed`, as you do in this pull request, breaks repeatability if the user is also using the native random module for his own purposes. To further clarify:

Initial code:
```
import random
import randomname
random.seed(myseed)
# some code
name_i_need_now = randomname.get_name()  # as of today
# code that uses random
# end WITH REPEATABLE RESULTS
```

After this edit is merged, his results change every time the code is run:
```
import random
import randomname
random.seed(myseed)
# some code
name_i_need_now = randomname.get_name()  # with this pull request merged
# code that uses random
# end WITH DIFFERENT RESULTS EACH TIME THE CODE IS RUN
```

Imho the ideal thing would be to have a separate "sandbox" RNG package-wide with absolutely no side effects. See [here](https://stackoverflow.com/a/61132227/9204395).
This would be beneficial in general, as today, even if a given code is repeatable, changing the usage of this package changes the results elsewhere (but then they stay the same).

**Comment by f-rosato** [comment]
For anyone interested, [here](https://gist.github.com/f-rosato/c11b124e656173ed0e3c1120246d4dd4) is a gist with a monkey patch that implements "fully sandboxed" RNG. It's ugly, but it works.

**Comment by luismavs** [comment]
Hi, you are of course fully right, the original proposed solution would not play nice with the RNG chain if the user is also using random module for purposes. 

I'm fine with your solution for sandboxing the RNG chain seems, I will incorporate it, thanks.

**Comment by luismavs** [comment]
I have added a quick implementation of @f-rosato's suggestion to sandbox the random number chain.

**Comment by luismavs** [comment]
Hi @beasteers , did you have a chance to look at this?

**Comment by beasteers** [comment]
Hey everyone thanks for your patience! I just got around to testing, lgtm!

**Comment by beasteers** [comment]
https://pypi.org/project/randomname/0.2.0/

**Pull request merged**
